{
 "title": "PostgreSQL Database",
 "description": "PostgreSQL monitoring dashboard for Prometheus using pg_exporter and custom metrics.",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock Mode",
    "query": "label_values(pg_lock_count{instance=\"$instance\",datname=~\"$datname\",mode=~\"AccessExclusiveLock|AccessShareLock|ExclusiveLock|RowExclusiveLock|RowShareLock|ShareLock|ShareRowExclusiveLock|ShareUpdateExclusiveLock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_meta_info{instance=\"$instance\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Start Time",
     "type": "stat",
     "description": "start time of the process",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(time() - pg_uptime{instance=\"$instance\"}) * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_connections{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total Rows Inserted",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  pg_db_tup_inserted{\r\n    instance=~\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n)"
      }
     ]
    },
    {
     "title": "Total Rows Updated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  pg_db_tup_updated{\r\n    instance=~\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n)"
      }
     ]
    },
    {
     "title": "Total Rows Fetched",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  pg_db_tup_fetched{\r\n    instance=~\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_shared_buffers{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_effective_cache_size{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_work_mem{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_maintenance_work_mem{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Wal Buffers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_custom_setting_wal_buffers{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Min WAL Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_min_wal_size{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_wal_size{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Checkpoint Completion Target",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_checkpoint_completion_target{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_custom_setting_random_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective IO Concurrency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_custom_setting_effective_io_concurrency{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Default Statistics Target",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_custom_setting_default_statistics_target{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_connections{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Autovacuum Max Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_autovacuum_max_workers{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 166 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_parallel_workers{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers Per Gather",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 169 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_parallel_workers_per_gather{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Maintenance Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 169 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_parallel_maintenance_workers{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Session Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "panels": [
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "pg_setting_max_connections{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Connection Usage %",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 * sum(pg_activity_count{instance=\"$instance\"}) / max(pg_setting_max_connections{instance=\"$instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_activity_count{instance=\"$instance\", datname=~\"$datname\", state=\"active\"})"
      }
     ]
    },
    {
     "title": "Idle Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_activity_count{instance=\"$instance\", datname=~\"$datname\", state=\"idle\"})"
      }
     ]
    },
    {
     "title": "Idle in Transaction",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 158 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_activity_count{instance=\"$instance\", datname=~\"$datname\", state=\"idle in transaction\"})"
      }
     ]
    },
    {
     "title": "Connections Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 162 },
     "targets": [
      {
       "expr": "sum by (state) (pg_activity_count{instance=\"$instance\", datname=~\"$datname\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(pg_activity_count{instance=\"$instance\", datname=~\"$datname\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Active Connections by User",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 170 },
     "targets": [
      {
       "expr": "sum by (usename) (\r\n  pg_custom_activity_count{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\",\r\n    state=\"active\"\r\n  }\r\n)",
       "legendFormat": "{{usename}}"
      }
     ]
    },
    {
     "title": "Idle Connections by User",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 170 },
     "targets": [
      {
       "expr": "sum by (usename) (\r\n  pg_custom_activity_count{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\",\r\n    state=\"idle\"\r\n  }\r\n)",
       "legendFormat": "{{usename}}"
      }
     ]
    },
    {
     "title": "Idle in Transaction by User",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 170 },
     "targets": [
      {
       "expr": "sum by (usename) (\r\n  pg_custom_activity_count{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\",\r\n    state=\"idle in transaction\"\r\n  }\r\n)",
       "legendFormat": "{{usename}}"
      }
     ]
    },
    {
     "title": "Active session Wait Events",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 177 },
     "targets": [
      {
       "expr": "sum by (wait_event_type, wait_event) (\r\n  pg_custom_activity_count{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\",\r\n    state=\"active\",\r\n    wait_event!=\"Running\"\r\n  }\r\n)",
       "legendFormat": "{{wait_event}} - {{wait_event_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Object size Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "TOP 10 large DBs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(10, pg_size_bytes{datname=~\"$datname\", instance=\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "DB sizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_size_bytes{datname=~\"$datname\", instance=\"$instance\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "TOP 20 large Tables",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20, pg_table_size_bytes{datname=~\"$datname\", instance=\"$instance\"}) by (datname)",
     "legendFormat": "{{datname}} / {{relname}}"
    }
   ]
  },
  {
   "title": "Tables size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_table_size_bytes{datname=~\"$datname\", instance=\"$instance\"}",
     "legendFormat": "{{datname}} / {{relname}}"
    }
   ]
  },
  {
   "title": "TOP 20 table Indexes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20, pg_custom_index_size_bytes{datname=~\"$datname\", instance=\"$instance\"}) by (datname)",
     "legendFormat": "{{datname}} / {{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Indexes size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_custom_index_size_bytes{datname=~\"$datname\", instance=\"$instance\"}\n",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Unused indexes",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  pg_custom_index_size_bytes{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n  and on(instance, datname, schemaname, relname, idxname)\r\n  (\r\n    pg_custom_index_idx_scan{\r\n      instance=\"$instance\",\r\n      datname=~\"$datname\"\r\n    } == 0\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_db_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "rate(pg_db_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_db_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_db_tup_updated{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_db_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_db_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_db_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(\r\n  pg_db_blks_hit{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\",\r\n    datname!~\"template0|template1\"\r\n  }[5m]\r\n)\r\n/\r\n(\r\n  rate(\r\n    pg_db_blks_hit{\r\n      instance=\"$instance\",\r\n      datname=~\"$datname\",\r\n      datname!~\"template0|template1\"\r\n    }[5m]\r\n  )\r\n  +\r\n  rate(\r\n    pg_db_blks_read{\r\n      instance=\"$instance\",\r\n      datname=~\"$datname\",\r\n      datname!~\"template0|template1\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_lock_count{\r\n  instance=~\"$instance\",\r\n  datname=~\"$datname\",\r\n  mode=~\"$mode\"\r\n} != 0",
     "legendFormat": "{{datname}} / {{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_db_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_db_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_checkpointer_timed{instance=\"$instance\"}[5m])",
     "legendFormat": "timed checkpoints/s"
    },
    {
     "expr": "rate(pg_checkpointer_req{instance=\"$instance\"}[5m])",
     "legendFormat": "requested checkpoints/s"
    }
   ]
  },
  {
   "title": "Replication stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "panels": [
    {
     "title": "Server Role",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 83 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_in_recovery{instance=\"$instance\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Replication lag sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 83 },
     "targets": [
      {
       "expr": "(\r\n  time() - pg_last_replay_time{instance=\"$instance\"}\r\n)\r\nand on(instance)\r\n(\r\n  pg_in_recovery{instance=\"$instance\"} == 1\r\n)",
       "legendFormat": "{{server}}, {{db}}"
      }
     ]
    },
    {
     "title": "Last Replay sec",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 87 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  time() - pg_last_replay_time{instance=\"$instance\"}\r\n)\r\nand on(instance)\r\n(\r\n  pg_in_recovery{instance=\"$instance\"} == 1\r\n)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "panels": [
    {
     "title": "TOP 100 Slow queries",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(\r\n  100,\r\n  pg_custom_query_mean_exec_time{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top Queries by Total Time",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(\r\n  100,\r\n  pg_custom_query_total_exec_time{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Most Called Queries",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(\r\n  100,\r\n  pg_custom_query_calls{\r\n    instance=\"$instance\",\r\n    datname=~\"$datname\"\r\n  }\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}